### ISSUE TITLE
Fatal error: The "path" argument must be of type string

### ISSUE THREAD

**Issue by takara** [takara/docker_comicbed#1]
>> Cleaned target dir /var/www/server/assets/vendor
Fatal error: The "path" argument must be of type string
/usr/lib/node_modules/tsd/node_modules/eslint-formatter-pretty/index.js:127
			} catch {
			        ^

SyntaxError: Unexpected token {
    at new Script (vm.js:51:7)
    at createScript (vm.js:136:10)
    at Object.runInThisContext (vm.js:197:10)
    at Module._compile (internal/modules/cjs/loader.js:618:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)

**Comment by takara** [comment]
```
$ nodejs -v
v9.11.2
$ npm -v
5.6.0
```
